create table if not exists public.fornitori (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null default '',
  cognome text not null default '',
  partita_iva text not null default ''
    check (partita_iva = '' or partita_iva ~ '^[0-9]{11}$'),
  telefono text not null default ''
    check (telefono = '' or telefono ~ '^[0-9]{6,11}$'),
  iban text not null default ''
    check (iban = '' or iban ~ '^IT[0-9]{2}[A-Z][0-9]{10}[A-Z0-9]{12}$'),
  mansione text not null default '',
  condominio_id bigint references public.condomini(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.fornitori enable row level security;

create policy "fornitori_select_own"
  on public.fornitori
  for select
  using (auth.uid() = user_id);

create policy "fornitori_insert_own"
  on public.fornitori
  for insert
  with check (auth.uid() = user_id);

create policy "fornitori_update_own"
  on public.fornitori
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "fornitori_delete_own"
  on public.fornitori
  for delete
  using (auth.uid() = user_id);
